# Generated by Django 5.0.6 on 2024-06-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantform',
            name='Address',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='applicantform',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=15),
        ),
    ]
