# Generated by Django 5.0.6 on 2024-06-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_applicantform_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentform',
            old_name='F_phone',
            new_name='F_number',
        ),
        migrations.RenameField(
            model_name='parentform',
            old_name='M_phone',
            new_name='M_number',
        ),
    ]
