# Generated by Django 5.0.6 on 2024-06-08 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_f_phone_parentform_f_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parentform',
            old_name='F_occupition',
            new_name='F_occupation',
        ),
        migrations.RenameField(
            model_name='parentform',
            old_name='M_occupition',
            new_name='M_occupaion',
        ),
    ]
